export type Responsibility = 
  // Performance Marketing
  | 'Google Ads'
  | 'Meta Ads'
  | 'LinkedIn Ads'
  | 'TikTok Ads'
  | 'YouTube Ads'
  | 'Programmatic Advertising'
  | 'Retargeting Campaigns'
  | 'Conversion Rate Optimization'
  | 'Bing Ads'
  | 'Apple Search Ads'
  | 'Spotify Ads'
  | 'Native Advertising'
  | 'Display Advertising'
  | 'Video Advertising'

  // E-commerce & Marketplaces
  | 'Amazon PPC'
  | 'Amazon SEO'
  | 'Amazon Listing Optimization'
  | 'Amazon Brand Store'
  | 'Amazon A+ Content'
  | 'Amazon Inventory Management'
  | 'Amazon FBA Strategy'
  | 'Walmart Marketplace'
  | 'eBay Optimization'
  | 'Etsy Shop Management'
  | 'Shopify Store Management'
  | 'WooCommerce Management'
  | 'BigCommerce Optimization'

  // Social Media Platforms
  | 'Pinterest Marketing'
  | 'Pinterest SEO'
  | 'Pinterest Ad Campaigns'
  | 'Pinterest Content Strategy'
  | 'Instagram Marketing'
  | 'Instagram Content Creation'
  | 'Instagram Story Strategy'
  | 'Instagram Reels Production'
  | 'Instagram Shop Setup'
  | 'TikTok Content Creation'
  | 'TikTok Trend Analysis'
  | 'TikTok Shop Management'
  | 'TikTok Live Strategy'
  | 'LinkedIn Company Page Management'
  | 'LinkedIn Content Strategy'
  | 'LinkedIn Lead Generation'
  | 'LinkedIn Personal Branding'
  | 'LinkedIn Sales Navigator'
  | 'Facebook Page Management'
  | 'Facebook Group Management'
  | 'Facebook Marketplace Strategy'
  | 'Facebook Shop Setup'
  | 'Meta Business Suite Management'
  | 'YouTube Channel Management'
  | 'YouTube SEO'
  | 'YouTube Shorts Strategy'
  | 'YouTube Community Management'
  | 'YouTube Monetization Strategy'
  | 'Twitter Marketing'
  | 'Twitter Ads Management'
  | 'Twitter Content Strategy'
  | 'Twitter Community Building'
  | 'Snapchat Marketing'
  | 'Snapchat AR Filters'
  | 'Snapchat Ads Management'
  | 'Discord Community Management'
  | 'Twitch Channel Management'
  | 'Reddit Marketing'
  | 'Telegram Channel Management'

  // SEO & Organic Growth
  | 'On-Page SEO'
  | 'Off-Page SEO'
  | 'Technical SEO'
  | 'SEO Audits'
  | 'Local SEO'
  | 'SEO Content Planning'
  | 'Google Business Profile Optimization'
  | 'Local Citation Building'
  | 'Review Management'

  // Analytics & Data
  | 'Google Analytics 4'
  | 'Facebook Analytics'
  | 'Data Visualization'
  | 'Custom Dashboard Creation'
  | 'Conversion Tracking Setup'
  | 'Heat Map Analysis'
  | 'User Behavior Analysis'
  | 'Tag Management'
  | 'UTM Setup & Management'
  | 'Pixel Implementation'

  // Content & Copywriting
  | 'Blog Writing'
  | 'Website Copywriting'
  | 'Email Campaign Copy'
  | 'Sales Copy'
  | 'Video Scriptwriting'
  | 'Case Studies'
  | 'Podcast Production & Strategy'
  | 'Webinar Management'
  | 'Online Course Creation'
  | 'Ebook Writing & Design'
  | 'Infographic Design'
  | 'White Paper Development'
  | 'Product Documentation'

  // Design & Creative
  | 'Brand Identity'
  | 'Ad Creative'
  | 'Web Design'
  | 'Social Media Design'
  | 'Pitch Deck Design'
  | 'Print Design'
  | 'Product Photography'
  | 'Motion Graphics'
  | 'UI/UX Design'
  | 'App Design'

  // Video & Audio
  | 'Video Production'
  | 'Animation'
  | 'Podcast Production'
  | 'Voiceover Work'
  | 'Video Editing'
  | 'Audio Editing'
  | 'Live Streaming'
  | 'Sound Design'

  // Email Marketing
  | 'Newsletter Creation'
  | 'Email Funnels'
  | 'Campaign Strategy'
  | 'List Growth Strategy'
  | 'Email Automation'
  | 'Email Template Design'
  | 'Email Deliverability'
  | 'A/B Testing'

  // Web & Tech
  | 'Website Development'
  | 'Landing Page Creation'
  | 'Analytics Setup'
  | 'CRM Integration'
  | 'Funnel Building'
  | 'API Integration'
  | 'Marketing Automation'
  | 'App Store Optimization (ASO)'
  | 'Mobile App Marketing'

  // Strategy & Analytics
  | 'Marketing Strategy'
  | 'Growth Hacking'
  | 'Marketing Audits'
  | 'Attribution Modeling'
  | 'Competitor Research'
  | 'Media Planning'
  | 'SaaS Marketing'
  | 'B2B Lead Generation'
  | 'Account-Based Marketing (ABM)'
  | 'Influencer Marketing Strategy'
  | 'Affiliate Program Management'

  // E-commerce Operations
  | 'Shopping Feed Optimization'
  | 'Marketplace Integration'
  | 'Order Management'
  | 'Inventory Sync'
  | 'Customer Service Setup'
  | 'Returns Management'
  | 'Cart Abandonment Strategy'
  | 'Cross-sell Strategy'
  | 'Upsell Implementation'
  | 'Customer Loyalty Programs'
  | 'Gift Card Programs'
  | 'Review Generation Strategy';

export type ServiceCategory =
  | 'Performance Marketing'
  | 'E-commerce & Marketplaces'
  | 'Social Media Platforms'
  | 'SEO & Organic Growth'
  | 'Analytics & Data'
  | 'Content & Copywriting'
  | 'Design & Creative'
  | 'Video & Audio'
  | 'Email Marketing'
  | 'Web & Tech'
  | 'Strategy & Analytics'
  | 'E-commerce Operations';

export interface Service {
  name: Responsibility;
  icon: string;
  category: ServiceCategory;
} 